from .arithmetic import router as arithmetic
from .logic import router as logic
from .grayscale import router as grayscale
from .histogram import router as histogram
from .equalize import router as equalize
from .specify import router as specify
from .convolution import router as convolution
from .fourier import router as fourier
from .noise_reduction import router as noise_reduction
from .statistics import router as statistics
from .rgb_array import router as rgb_array
from .zero_padding import router as zero_padding
from .filter import router as filter
from .periodic_noise import router as periodic_noise